### PR TITLE
nf18: Add Zephyr port and move Arduino implementation into a new directory.

### PR DESCRIPTION
**Pull request by haydenroche5**

### CODE REVIEW

**Comment by m-mcgowan** [comment]
[NF18 - Zephyr port](https://trello.com/c/UCSL7AU7/198-nf18-zephyr-port)

**Comment by zfields** [comment]
Should we also throw the `.devcontainer/devcontainer.json` and the `Dockerfile` in here, or should we just leave NF9 as a one off?

**Comment by haydenroche5** [comment]
> Should we also throw the `.devcontainer/devcontainer.json`, `.vscode/tasks.json`, `.vscode/launch.json`, `.vscode/settings.json` and the `Dockerfile` in here, or should we just leave NF9 as a one off?

Yeah I can do that.

**Comment by haydenroche5** [comment]
Added the various VS Code files and improved the Zephyr README.md.

**Review by zfields — APPROVED** [review]

**Pull request merged**
